name: Company Discovery

on:
  workflow_dispatch:

jobs:
  discover:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Show files
        run: |
          pwd
          ls -R

      - name: Run scraper
        run: |
          python Company_Discovery.py
